Vagrant.configure("2") do |config|

  config.vm.define "client" do |client|
    client.vm.box = "ubuntu/jammy64"
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.56.10"
  end

  config.vm.define "bck" do |bck|
    bck.vm.box = "ubuntu/jammy64"
    bck.vm.hostname = "bck"
    bck.vm.network "private_network", ip: "192.168.56.11"
  end
config.vm.provision "ansible" do |ansible|
  ansible.playbook = "ansible/playbook.yml"
ansible.inventory_path = "ansible/inventory"
end
end
