Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/jammy64"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.56.10"
  end

  config.vm.define "log" do |log|
    log.vm.box = "ubuntu/jammy64"
    log.vm.hostname = "log"
    log.vm.network "private_network", ip: "192.168.56.11"
  end
config.vm.provision "ansible" do |ansible|
  ansible.playbook = "ansible/playbook.yml"
ansible.inventory_path = "ansible/inventory"
end
end
