MACHINES = {
  :"pam" => {
    :box_name => "ubuntu/jammy64",
    :cpus => 2,
    :memory => 1024,
    :ip => "192.168.57.10",
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|

    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.network "private_network", ip: boxconfig[:ip]

    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s

      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end

      box.vm.provision "shell", inline: <<-SHELL
        set -e

       
        sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config

        if [ -d /etc/ssh/sshd_config.d ]; then
          echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
        fi

        systemctl restart sshd

        echo "Создание пользователей и группы"

        useradd -m -s /bin/bash otus || true
        useradd -m -s /bin/bash otusadm || true

        echo "otus:Otus2022!" | chpasswd
        echo "otusadm:Otus2022!" | chpasswd

        

        groupadd -f admin

        usermod -aG admin otusadm
        usermod -aG admin root
        usermod -aG admin vagrant


        cat << 'EOF' > /usr/local/bin/login.sh
#!/bin/bash

if [ "$(date +%a)" = "Sat" ] || [ "$(date +%a)" = "Sun" ]; then
  if getent group admin | grep -qw "$PAM_USER"; then
    exit 0
  else
    exit 1
  fi
else
  exit 0
fi
EOF

        chmod +x /usr/local/bin/login.sh

        echo "Настройка PAM"

        PAM_FILE="/etc/pam.d/sshd"

        if ! grep -q "pam_exec.so /usr/local/bin/login.sh" $PAM_FILE; then
          sed -i '/^@include common-auth/a auth required pam_exec.so /usr/local/bin/login.sh' $PAM_FILE
        fi

        
        sshd -T | grep passwordauthentication

        echo "completed!"
      SHELL
    end
  end
end
