# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  inetRouter: {
    box_name: "centos/7",
    net: [
      {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
    ]
  },
  centralRouter: {
    box_name: "centos/7",
    net: [
      {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
      {ip: '192.168.0.1',   adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
      {ip: '192.168.0.33',  adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
      {ip: '192.168.0.65',  adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "mgt-net"},
      {ip: '192.168.255.5', adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "office1-central"},
      {ip: '192.168.255.9', adapter: 7, netmask: "255.255.255.252", virtualbox__intnet: "office2-central"},
    ]
  },
  centralServer: {
    box_name: "centos/7",
    net: [
      {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
    ]
  },
  office1Router: {
    box_name: "centos/7",
    net: [
      {ip: '192.168.255.6', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "office1-central"},
      {ip: '192.168.2.1',   adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "office1-dev"},
      {ip: '192.168.2.65',  adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "office1-test"},
      {ip: '192.168.2.129', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "office1-mgt"},
      {ip: '192.168.2.193', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "office1-hw"},
    ]
  },
  office2Router: {
    box_name: "centos/7",
    net: [
      {ip: '192.168.255.10', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "office2-central"},
      {ip: '192.168.1.1',    adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "office2-dev"},
      {ip: '192.168.1.129',  adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "office2-test"},
      {ip: '192.168.1.193',  adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "office2-hw"},
    ]
  },
  office1Server: {
    box_name: "centos/7",
    net: [
      {ip: '192.168.2.2', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "office1-dev"},
    ]
  },
  office2Server: {
    box_name: "centos/7",
    net: [
      {ip: '192.168.1.2', adapter: 2, netmask: "255.255.255.128", virtualbox__intnet: "office2-dev"},
    ]
  },
}

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true

  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s

      boxconfig[:net].each do |ipconf|
        box.vm.network :private_network, **ipconf
      end

      if boxconfig.key?(:public)
        box.vm.network :public_network, **boxconfig[:public]
      end

      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL

      box.vm.provision "ansible" do |ansible|
        ansible.playbook = "provisioning/playbook.yml"
        ansible.become = true
        ansible.compatibility_mode = "2.0"
        if boxconfig[:box_name].include?("centos/6")
          ansible.extra_vars = { ansible_python_interpreter: "/usr/bin/python2" }
        end
      end
    end
  end
end
